### ISSUE TITLE
Add operators for rlc 

### ISSUE THREAD

**Issue by heathergrant** [instituteofcancerresearch/pisca-box#24]
Please could the following operators be added to the XML when users select a random local clock model?

```
<operators id="operators" optimizationSchedule="default">
......
	<scaleOperator scaleFactor="0.75" weight="15">
		<parameter idref="localClock.relativeRates"/>
	</scaleOperator>
	<bitFlipOperator weight="15">
			<parameter idref="localClock.changes"/>
	</bitFlipOperator>
.....
</operators>
```

**Comment by rachelicr** [comment]
Could you attach an xml file that has this operator in - the entire thing? I need to make sure it is referenced correctly throughout the xml.

**Comment by rachelicr** [comment]
Don't worry - I have an example in the 4 xml files you sent.

**Comment by rachelicr** [comment]
They ought to be there automatically, I made it so that all operators and priors are automatically in the logs.

**Comment by rachelicr** [comment]
Can you check with the new version that it is as you think it should be then let me know?

**Comment by heathergrant** [comment]
All as expected! Thanks!
