### ISSUE TITLE
Alignment and taxa block 

### ISSUE THREAD

**Issue by heathergrant** [instituteofcancerresearch/pisca-box#40]
Appears alignment and taxa block are not being written out with a local fasta file

**Comment by rachelicr** [comment]
Fix 1. For any errors that cause the alignment or taxa block to be empty, I add a comment in the block about the error:
```
<taxa id="taxa">
	<!-- No taxa, is there an input error? The ages need to match the sequences. -->
</taxa>
```

```
<alignment id="alignment">
	<dataType idref="biallelicBinary"/>
	<!-- No alignnents, is there an input error? The ages need to match the sequences. -->
</alignment>
```

**Comment by rachelicr** [comment]
Fix 2. I strip the data in the csv file so this particular case does not cause a problem.
